### ISSUE TITLE
Vuex-usm Examples

### ISSUE THREAD

**Issue by Lionad-Morotar** [unadlib/usm#1]
可以给一个 vuex-usm 的使用文档么 ~
Need a vuex-usm usage document support ~

**Comment by unadlib** [comment]
Here is an [example](https://github.com/unadlib/usm-examples/tree/master/packages/todo-vue) with `vuex-usm`. USM is an universal design, so their usage is the same. The part connected to Vue is different, but the connection usage is the same as the Vuex.

**Comment by Lionad-Morotar** [comment]
> Here is an [example](https://github.com/unadlib/usm-examples/tree/master/packages/todo-vue) with `vuex-usm`. USM is an universal design, so their usage is the same. The part connected to Vue is different, but the connection usage is the same as the Vuex.

thank for that ~
