### ISSUE TITLE
"watch" deep equality

### ISSUE THREAD

**Issue by rwest202** [unadlib/usm#50]
I have been using the watch function like so:

```
import { app } from '../store' // App is a module class

watch(
    app,
    () => app.customer,
    () => {
        // Do something with data
    }
);
```

However, I want to now watch for two properties at the same time

```
watch(
    app,
    () => [app.customer, app.announcement],
    () => {
        // Do something with data
    }
);
```

The watch function seems to use a `===` check for equality but I don't think this captures all the changes that may occur. What if a nested property changes, I don't believe the current logic will catch it.

**Comment by unadlib** [comment]
> I have been using the watch function like so:
> 
> ```
> import { app } from '../store' // App is a module class
> 
> watch(
>     app,
>     () => app.customer,
>     () => {
>         // Do something with data
>     }
> );
> ```
> 
> However, I want to now watch for two properties at the same time
> 
> ```
> watch(
>     app,
>     () => [app.customer, app.announcement],
>     () => {
>         // Do something with data
>     }
> );
> ```
> 
> The watch function seems to use a `===` check for equality but I don't think this captures all the changes that may occur. What if a nested property changes, I don't believe the current logic will catch it.

If you are using `usm-redux`, you actually need to use `@compted` to combine the values you need to observe into a getter. for example, 

```ts
class Counter {
  constructor() {
    watch(
      this,
      () => this.counts,
      () => {
        //
      }
    )
  }

  @state
  count0 = 0;

  @state
  count1 = 0;

  @computed((that: Counter) => [this.count0, this.count1])
  get counts() {
    return [this.count0, this.count1]
  }
}
```

In fact, I'm thinking about implementing a cleaner API `watchEffect` for watching multiple values. But I doubt if there will be many people who need it.

**Comment by unadlib** [comment]
Hi @rwest202, this issue has been solved and I have released version 3.9.0.

You can pass the option `{ multiple: true }`, which will support watching multiple values.

For example,

```ts
class Counter {
  constructor() {
    watch(
      this,
      () => [this.count0, this.count1],
      ([newCount0, newCount1], [oldCount0, oldCount0]) => {
        //
      },
      {
        multiple: true,
      }
    );
  }

  @state
  count0 = 0;

  @state
  count1 = 0;
}
```

**Comment by rwest202** [comment]
I'm using plain `usm` it's a great package, thanks for the support!

**Comment by rwest202** [comment]
Do you think the `isEqual` function would be better as a deep equality check. I still would like to pass in objects that may change only slightly in nested places, like in the case of an api response. Perhaps an option for this

**Comment by unadlib** [comment]
> Do you think the `isEqual` function would be better as a deep equality check. I still would like to pass in objects that may change only slightly in nested places, like in the case of an api response. Perhaps an option for this

Could you give a specific example?

**Comment by unadlib** [comment]
In usm v3.9.1, `watch` API add `isEqual` option.
