### ISSUE TITLE
any nextjs examples?

### ISSUE THREAD

**Issue by p32929** [unadlib/usm#55]
Hello, thanks for creating this amazing library. I just wanted to test it out with nextjs & not sure, what I've done wrong, but I'm getting this error:
![image](https://user-images.githubusercontent.com/6418354/172976733-e943d8f5-749e-46d0-8691-8f9abc6a4cc1.png)

Is there any nextjs example with usm-redux?
Thanks

**Comment by unadlib** [comment]
In fact, you can use `usm-redux` similar to how `redux` is used in `nextjs`, the only thing you need to do is to enable support for decorators.

From the screenshot, you are using TS, but you don't have enabled `experimentalDecorators`

**Comment by p32929** [comment]
I have one more question:
When we look at the react example in this link ( https://github.com/unadlib/usm-redux-demo ), in the App component, we have to call `  const count = useSelector(() => counter.count);`, right? But lets say, we want to access the states outside of the component or if we want to change states from outside of a component, how do we do that?

Thanks :)

**Comment by unadlib** [comment]
`const count = useSelector(() => counter.count);` 

`useSelector` is used by React components to access the Redux state. Based on the design of `usm-redux`, you can call `counter.increase()` anywhere, and you will see the re-rendered and updated state in this component.

**Comment by p32929** [comment]
Hi, thank you so much for your answer. I have managed to make it work with NextJS.
