### ISSUE TITLE
How to use it with redux devtools?

### ISSUE THREAD

**Issue by xoka4** [unadlib/usm#57]
in this post ( https://unadlib.medium.com/a-concise-design-that-completely-changed-redux-e95d6b76bd8b ) you've commented that it can be used with redux-devtools. But its not showing the states or actions. any solution?

**Comment by unadlib** [comment]
You can view the document https://github.com/reduxjs/redux-devtools/tree/main/extension

For example,
```ts
import React from "react";
import ReactDOM from "react-dom";
import { Provider } from "react-redux";
import { createStore } from "usm-redux";
import { compose } from "redux";
import "./index.css";
import App from "./App";
import reportWebVitals from "./reportWebVitals";
import { Counter } from "./counter.service";

const counter = new Counter();

const composeEnhancers =
  // @ts-ignore
  typeof window === "object" && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
    ? // @ts-ignore
      window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({
        // Specify extension’s options like name, actionsDenylist, actionsCreators, serialize...
      })
    : compose;

// const reduxEnhancer = composeEnhancers(
//   applyMiddleware(...middleware)
//   // other store enhancers if any
// );

const store = createStore(
  {
    modules: [counter],
  },
  undefined,
  {
    reduxEnhancer: composeEnhancers(),
  }
);

ReactDOM.render(
  <React.StrictMode>
    <Provider store={store}>
      <App counter={counter} />
    </Provider>
  </React.StrictMode>,
  document.getElementById("root")
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

```

**Comment by xoka4** [comment]
Thanks for the reply. I really appreciate. but I guess, I'm not that knowledgable yet to understand the solution. Would you mind sharing a sample project source code with the solution? Thanks a lot

**Comment by xoka4** [comment]
Hello, would you please be kind enough to make a tutorial on how to do that? Thanks a million 
( I've tried what you've mentioned in your comment, but it doesn't seem to work. not sure why )

**Comment by unadlib** [comment]
@xoka4 , I've updated the example https://github.com/unadlib/usm-redux-demo. Sorry, there was an issue with the example.

Feel free to use it. And by the way, there is a framework based on this implementation [reactant](https://github.com/unadlib/reactant).

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/18650460/185774056-ea1a1651-9151-4526-b830-743227f5831c.png">

**Comment by xoka4** [comment]
Thanks a lot. I'll check the repo today.
