### ISSUE TITLE
example use @computed decorator

### ISSUE THREAD

**Issue by riskihajar** [unadlib/usm#6]
how to use a computed decorator?

i tried but got an error
`@computed accessToken = this.token`

and the error
`Cannot set property accessToken of #<Auth> which has only a getter`

**Comment by unadlib** [comment]
`accessToken` doesn't look like it needs to be computed.

If you need it:
```js
@computed accessToken = [
  () => this.token,
  (token) => {
    // compute result
    return result
  }
]
```

If you use `usm-mobx` or `usm-vuex`, it's more succinct.

```js
@computed
get accessToken() {
    // use this.token  to compute result
    return result
}
```

**Comment by riskihajar** [comment]
nice, it's working, thanks
